### ISSUE TITLE
Not working in latest greenshot unstable - any plans to support?

### ISSUE THREAD

**Issue by dodgyrabbit** [Rohland/Fogshot#1]
I managed to get this working using the version you mention in the readme. Very useful indeed!

Doesn't seem to "pick up" the plugin with the latest greenshot version - but I realize you don't actually support it.
Any plans to support it? I could try help if you point me in the right direction as I use fogbugz and greenshot extensively. Never really liked the fogbugz screenshot tool as it has very limited editing capabilities.

FYI: Something else I noticed - if your credentials are entered wrong, Fogshot gives a very generic "something went wrong" error that seems like the plugin actually failed. Suggest maybe a more friendly error message.

**Comment by Rohland** [comment]
The upgrade popup is starting to get annoying. I'll hopefully attend to this soon.

**Comment by Cannot-find-an-unused-username** [comment]
Any chance you could update this to work with Greenshot 1.0?  Would greatly appreciate it if you did.  Thanks.

**Comment by dodgyrabbit** [comment]
I guess it's time.
